// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTagToAsset(arg1:number,arg2:string):Promise<Array<main.Tag>>;

export function AddToCollection(arg1:number,arg2:number):Promise<void>;

export function AddWatchFolder():Promise<Array<main.Asset>>;

export function BulkAddToCollection(arg1:number,arg2:Array<number>):Promise<void>;

export function BulkSetFavorite(arg1:Array<number>,arg2:boolean):Promise<void>;

export function BulkTagAssets(arg1:Array<number>,arg2:string):Promise<void>;

export function CreateCollection(arg1:string,arg2:string):Promise<main.Collection>;

export function DeleteCollection(arg1:number):Promise<void>;

export function GetAllTags():Promise<Array<main.Tag>>;

export function GetAssets():Promise<Array<main.Asset>>;

export function GetAssetsByTag(arg1:string):Promise<Array<main.Asset>>;

export function GetAssetsByTags(arg1:Array<string>):Promise<Array<main.Asset>>;

export function GetCollectionAssets(arg1:number):Promise<Array<main.Asset>>;

export function GetCollections():Promise<Array<main.Collection>>;

export function GetCollectionsForAsset(arg1:number):Promise<Array<main.Collection>>;

export function GetFavoritedAssets():Promise<Array<main.Asset>>;

export function GetFileServerURL():Promise<string>;

export function GetRecentlyAddedAssets():Promise<Array<main.Asset>>;

export function GetRecentlyUsedAssets():Promise<Array<main.Asset>>;

export function GetTagsForAsset(arg1:number):Promise<Array<main.Tag>>;

export function GetTagsWithCounts():Promise<Array<main.TagWithCount>>;

export function GetThumbnail(arg1:number):Promise<string>;

export function GetUntaggedAssets():Promise<Array<main.Asset>>;

export function GetWatchFolders():Promise<Array<main.WatchFolder>>;

export function MarkAssetUsed(arg1:number):Promise<void>;

export function OpenFileInFolder(arg1:string):Promise<void>;

export function PingBlender():Promise<main.BlenderStatus>;

export function RemoveFromCollection(arg1:number,arg2:number):Promise<void>;

export function RemoveTagFromAsset(arg1:number,arg2:number):Promise<Array<main.Tag>>;

export function RemoveWatchFolder(arg1:number):Promise<void>;

export function RenameCollection(arg1:number,arg2:string):Promise<void>;

export function RescanFolder(arg1:number):Promise<Array<main.Asset>>;

export function SaveThumbnail(arg1:number,arg2:string):Promise<void>;

export function SendToBlender(arg1:Array<string>):Promise<main.BlenderStatus>;

export function ToggleFavorite(arg1:number):Promise<boolean>;
