// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToAsset(arg1, arg2) {
  return window['go']['main']['App']['AddTagToAsset'](arg1, arg2);
}

export function AddToCollection(arg1, arg2) {
  return window['go']['main']['App']['AddToCollection'](arg1, arg2);
}

export function AddWatchFolder() {
  return window['go']['main']['App']['AddWatchFolder']();
}

export function BulkAddToCollection(arg1, arg2) {
  return window['go']['main']['App']['BulkAddToCollection'](arg1, arg2);
}

export function BulkSetFavorite(arg1, arg2) {
  return window['go']['main']['App']['BulkSetFavorite'](arg1, arg2);
}

export function BulkTagAssets(arg1, arg2) {
  return window['go']['main']['App']['BulkTagAssets'](arg1, arg2);
}

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetAssetsByTag(arg1) {
  return window['go']['main']['App']['GetAssetsByTag'](arg1);
}

export function GetAssetsByTags(arg1) {
  return window['go']['main']['App']['GetAssetsByTags'](arg1);
}

export function GetCollectionAssets(arg1) {
  return window['go']['main']['App']['GetCollectionAssets'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetCollectionsForAsset(arg1) {
  return window['go']['main']['App']['GetCollectionsForAsset'](arg1);
}

export function GetFavoritedAssets() {
  return window['go']['main']['App']['GetFavoritedAssets']();
}

export function GetFileServerURL() {
  return window['go']['main']['App']['GetFileServerURL']();
}

export function GetRecentlyAddedAssets() {
  return window['go']['main']['App']['GetRecentlyAddedAssets']();
}

export function GetRecentlyUsedAssets() {
  return window['go']['main']['App']['GetRecentlyUsedAssets']();
}

export function GetTagsForAsset(arg1) {
  return window['go']['main']['App']['GetTagsForAsset'](arg1);
}

export function GetTagsWithCounts() {
  return window['go']['main']['App']['GetTagsWithCounts']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetUntaggedAssets() {
  return window['go']['main']['App']['GetUntaggedAssets']();
}

export function GetWatchFolders() {
  return window['go']['main']['App']['GetWatchFolders']();
}

export function MarkAssetUsed(arg1) {
  return window['go']['main']['App']['MarkAssetUsed'](arg1);
}

export function OpenFileInFolder(arg1) {
  return window['go']['main']['App']['OpenFileInFolder'](arg1);
}

export function PingBlender() {
  return window['go']['main']['App']['PingBlender']();
}

export function RemoveFromCollection(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromCollection'](arg1, arg2);
}

export function RemoveTagFromAsset(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromAsset'](arg1, arg2);
}

export function RemoveWatchFolder(arg1) {
  return window['go']['main']['App']['RemoveWatchFolder'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RescanFolder(arg1) {
  return window['go']['main']['App']['RescanFolder'](arg1);
}

export function SavePolyCount(arg1, arg2) {
  return window['go']['main']['App']['SavePolyCount'](arg1, arg2);
}

export function SaveThumbnail(arg1, arg2) {
  return window['go']['main']['App']['SaveThumbnail'](arg1, arg2);
}

export function SendToBlender(arg1) {
  return window['go']['main']['App']['SendToBlender'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
